---
version: '3.7'

services:
  postgres:
    image: debezium/postgres:12
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-pw
      POSTGRES_DB: mydb
    volumes:
      - "./conf/custom-config.conf:/etc/postgresql/postgresql.conf"
      - "./postgres-data:/var/lib/postgresql/data"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf 
  